train:
  seq_length: 512
  epochs: 10000
  total_steps: 120000
  batch_size: 4

  checkpoint_interval: 10000
  eval_interval: 1000

  pipeline: "PromptPipeline"
  trainer: "AcceleratePPOTrainer"
  tracker: wandb
  project_name: trlx
  entity_name: open-assistant

model:
  model_path: "CarperAI/openai_summarize_tldr_sft"
  num_layers_unfrozen: 2

tokenizer:
  tokenizer_path:
  truncation_side: "right"
  padding_side: "left"

optimizer:
  name: "adamw"
  kwargs:
    lr: 1.0e-6
    betas: [0.9, 0.999]
    eps: 1.0e-8
    weight_decay: 0.01

scheduler:
  name: "cosine_annealing"
  kwargs:
    T_max: 100000
    eta_min: 5.0e-6

method:
  name: "ppoconfig"
  num_rollouts: 32
  chunk_size: 4
  ppo_epochs: 2
  init_kl_coef: 0.1
  target: 6
  horizon: 10000
  gamma: 1
  lam: 0.95
  cliprange: 0.2
  cliprange_value: 0.2
  vf_coef: 0.2
  scale_reward: False
  ref_mean: null
  ref_std: null
  cliprange_reward: 4
  gen_kwargs:
    max_new_tokens: 400
    top_p: 0.95
    top_k: 1000
    typical_p: 0.95
    repetition_penalty: 1.2